git:
  scanPath: /home/icy/code/tmp/testrepos
  readme:
    - readme
    - README
    - readme.md
    - README.md
template:
  dir: ./templates
meta:
  title: git good
  description: i think it's a skill issue
